version: "2"

services:
  bind:
    image: sameersbn/bind:9.9.5-20170129
    container_name: bind
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 10000:10000/tcp
    volumes:
      - bind:/data

volumes:
  bind:
